---
all:
  vars:
    ansible_become: true
    # Optional override per environment.
    # ansible_user: alejandro

  children:
    preprod:
      children:
        ark:
          hosts:
            ark-pp-001:
              ansible_host: 192.168.1.101
