---
all:
  vars:
    ansible_become: true
    # ansible_user is set to 'arkadmin' in group_vars/all.yml
    # This is the shared admin account used by developers

  children:
    preprod:
      children:
        ark:
          hosts:
            ark-pp-001:
              ansible_host: 192.168.1.101
              ark_hostname: ark-pp-001
