---
all:
  vars:
    ansible_become: true
    # Optional override. Prefer setting remote_user in ansible.cfg or via SSH config.
    # ansible_user: alejandro

  children:
    prod:
      children:
        ark:
          hosts:
            ark-001:
              ansible_host: 192.168.1.201
            ark-002:
              ansible_host: 192.168.1.202
