---
# Global defaults (prod)

timezone: Europe/Oslo

# Placeholder admin user. This is the account you SSH as.
ark_admin_user: alejandro

ark_app_user: arkapp
ark_app_group: arkapp

ark_app_base_dir: /opt/arkapp
ark_app_data_dir: /var/lib/arkapp
ark_app_log_dir: /var/log/arkapp

# Placeholder NIC name. Confirm via `ip link` on the device.
ark_nic_name: enp0s25

