---
- name: Restart systemd-networkd
  ansible.builtin.systemd:
    name: systemd-networkd
    state: restarted

- name: Restart dnsmasq
  ansible.builtin.systemd:
    name: dnsmasq
    state: restarted
